japama/urls.py
from django.contrib import admin
from django.urls import include, path
 
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('kanas/', include('kanas.urls')),
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('ages/', include('antorsioa.urls')),
    path('katas/', include('kata.urls')),
]

kata/urls.py
from django.urls import (path, re_path)
from django.conf.urls import include

from .views import Katas, Register
from .views.globe import GlobeView, Create, QuestionView, ResultsView, UserResultsView, Activate, Edit
from .views.katatoeba import ExampleView, NewExample, Validate, EditExample, EditSingleExample

common_patterns = [
    path('',          Katas.as_view(),    name='katas'    ),
    path('register/', Register.as_view(), name='register' ),
]

globe_patterns = [
    path    ('globe/',                                              GlobeView.as_view(),       name='globe'     ),
    path    ('globe/create/',                                       Create.as_view(),          name='create'    ),
    path    ('globe/activate/',                                     Activate.as_view(),        name='activate'  ),
    re_path ('globe/(?P<miniglobe>\w+)/$',                          QuestionView.as_view(),    name='questions' ),
    re_path ('globe/(?P<miniglobe>\w+)/edit/$',                     Edit.as_view(),            name='edit'      ),
    re_path ('globe/(?P<miniglobe>\w+)/results/$',                  ResultsView.as_view(),     name='results'   ),
    re_path ('globe/(?P<miniglobe>\w+)/results/(?P<user_id>\w+)/$', UserResultsView.as_view(), name='uresults'  ),
]

katatoeba_patterns = [
    path   ('katatoeba/',                   ExampleView.as_view(),       name='katatoeba'          ),
    path   ('katatoeba/create/',            NewExample.as_view(),        name='createexample'      ),
    path   ('katatoeba/validate/',          Validate.as_view(),          name='validate'           ),
    path   ('katatoeba/edit/',              EditExample.as_view(),       name='editexample'        ),
    re_path('katatoeba/edit/(?P<id>\w+)/$', EditSingleExample.as_view(), name='editsingleexample'  ),
]
urlpatterns = common_patterns + globe_patterns + katatoeba_patterns

kata/models/globe.py
from django.db import models
from django.contrib.auth.models import User

DIFFS = [
    { 'value': 'BA', 'text': 'Basics' },
    { 'value': 'EZ', 'text': 'Easy' },
    { 'value': 'IM', 'text': 'Intermediary' },
    { 'value': 'DF', 'text': 'Difficult' },
    { 'value': 'MR', 'text': 'Muri' },
    { 'value': 'MD', 'text': 'Muda' },
]

class Globe(models.Model):
    theme = models.CharField(max_length=1000)
    mini = models.CharField(max_length=30)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    doc = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)
    def __str__(self):
        return self.theme

class Question(models.Model):
    text = models.CharField(max_length=1000)
    qtype = models.CharField(
        max_length=2,
        choices= [
            ('MC', 'Multi Choice'),
            ('SC', 'Single Choice'),
            ('TA', 'Text Answer'),
        ],
        default='MC',
    )
    diff = models.CharField(
        max_length=2,
        choices= [ (diff['value'], diff['text']) for diff in DIFFS ],
        default='EZ',
    )
    answer  = models.CharField(max_length=300, default='', blank=True)
    answer1 = models.CharField(max_length=300, default='', blank=True)
    answer2 = models.CharField(max_length=300, default='', blank=True)
    answer3 = models.CharField(max_length=300, default='', blank=True)
    answer4 = models.CharField(max_length=300, default='', blank=True)
    answer5 = models.CharField(max_length=300, default='', blank=True)
    answer6 = models.CharField(max_length=300, default='', blank=True)
    globe = models.ForeignKey(
        Globe,
        on_delete=models.CASCADE
    )
    def __str__(self):
        return self.text

class Resolution(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    dor = models.DateField(auto_now_add=True)
    answers = models.CharField(max_length=3000)
    globe = models.ForeignKey(
        Globe,
        on_delete=models.CASCADE
    )
    def __str__(self):
        return f'{str(self.user)}_{self.globe.theme}'

kata/models/katatoeba.py
from django.contrib.auth.models import User
from django.db import models

class Example(models.Model):
    french = models.CharField(max_length=1000)
    japanese = models.CharField(max_length=1000)
    tags = models.CharField(max_length=3000)
    validated = models.BooleanField(default=True)
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    comment = models.CharField(max_length=3000, default='')
    def __str__(self):
        return self.french

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    examples = models.ManyToManyField(Example)
    def __str__(self):
        return self.name

kata/views/katas.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View

from .utils import render_page

class Katas(LoginRequiredMixin, View):
    def get(self, request):
        return render_page(request, 'katas.html', 'Katas', {})

kata/views/register.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views import View

class Register(View):
    def get(self, request):
        return render(request, 'register.html', { 'form': UserCreationForm() })

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('/')

        return render(request, 'register.html', { 'form': form })

kata/views/utils.py
from django.shortcuts import render
from django.http import Http404

# All keys MUST BE UNIQUE!
# This tree is used to generate crumbs
TREE = {
    'Home': {
        'Katas': {
            'G.L.O.B.E.': {
                '_globe_': {
                    'Results': {
                        '_result_user_': {}
                    },
                    'Edit globe': {}
                },
                'Create globe': {},
                'Activate globes': {}
            },
            'Katatoeba': {
                'Create example': {},
                'Edit examples': {},
                'Validate examples': {
                    '_edit_example_': {}
                }
            }
        }
    }
}

def path_to_key(leaf, path=[], tree=TREE):
    for key, _ in tree.items():
        if(key == leaf):
            return { 'found': True, 'path': path }
    for key, next in tree.items():
        res = path_to_key(leaf, path+[key], next)
        if(res['found']):
            return res
    return { 'found': False, 'path': path }

def render_page(request, template, title, context, vars={}):
    path_finder = path_to_key(title)
    if(path_finder['found']):
        return render(request, template, { 'title': title if title not in vars else vars[title], 'crumbs': crumbs(path_finder['path']+[title], vars), **context })
    else:
        raise Http404('Page not found')

def crumbs(crumbs, vars):
    redirs = ['../'*(len(crumbs)-n-1) if n != len(crumbs)-1 else './' for n in range(len(crumbs))]
    return { (el[0] if el[0] not in vars else vars[el[0]]): el[1] for el in zip(crumbs, redirs) }

kata/templates/katatoeba/create.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-4">
    <form>
        {% csrf_token %}
        <div class="form-group">
            <label for="french">
                Phrase en français :
            </label>
            <input type="text" class="form-control" id="french" name="french" placeholder="Ceci est un stylo.">
        </div>
        <div class="form-group">
            <label for="japanese">
                Phrase en japonais :
            </label>
            <input type="text" class="form-control" id="japanese" name="japanese" placeholder="これはペンです">
        </div>
        <div class="form-group">
            <label for="japanese">
                Tags séparés d'une virgule :
            </label>
            <input type="text" class="form-control" id="tags" name="tags" placeholder="TE form, passé, négation, ...">
        </div>
        <button type="submit" formmethod="post" class="btn btn-primary">
            Submit
        </button>
    </form>
</div>
{% endblock %}

kata/templates/katatoeba/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-4">
    <form>
        {% csrf_token %}
        {% for example in examples %}
        <div class="form-group">
            <label for="french">
                De {{ example.user.username }} :
            </label>
            <input type="text" class="form-control" id="french" name="french {{ example.id }}" value="{{ example.french }}">
            <input type="text" class="form-control" id="japanese" name="japanese {{ example.id }}" value="{{ example.japanese }}">
            <input type="text" class="form-control" id="tags" name="tags {{ example.id }}" value="{{ example.tags }}">
            {% if example.comment != '' %}
            <p class="text-warning">
                {{ example.comment }}
            </p>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" formmethod="post" class="btn btn-primary">
            Submit
        </button>
    </form>
</div>
{% endblock %}

kata/templates/katatoeba/example.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-4">
    <form>
        {% csrf_token %}
        <select name="tags" id="example" class="form-control"  multiple="multiple" style="display: none;">
        {% for tag in tags %}
            <option value="{{ tag.name }}"{% if tag.name in ctags %} selected{% endif %}>{{ tag.name }}</option>
        {% endfor %}
        </select>
        <button type="submit" formmethod="post" class="btn btn-primary waves-effect waves-light">
            Apply
        </button>
        <select name="type" id="type">
            {% if type == 'and' %}
            <option value="and">ET</option>
            <option value="or">OU</option>
            {% else %}
            <option value="or">OU</option>
            <option value="and">ET</option>
            {% endif %}
        </select>
        <select name="lang" id="lang">
            {% if lang == 'FR' %}
            <option value='FR'>FR>JP</option>
            <option value='JP'>JP>FR</option>
            {% else %}
            <option value='JP'>JP>FR</option>
            <option value='FR'>FR>JP</option>
            {% endif %}
        </select>
    </form>
    <hr>
    <a href='create'>
        <button class="btn btn-primary waves-effect waves-light">
            Add new example
        </button>
    </a>
    <a href='edit'>
        <button class="btn btn-primary waves-effect waves-light">
            Edit examples
        </button>
    </a>
    <a href='validate'>
        <button class="btn btn-primary waves-effect waves-light"{% if not perms.kata.change_example %} disabled{% endif %}>
            Validate
        </button>
    </a>
    {% for example in examples %}
        <div class="card" style="width: 40rem;" >
            <a onclick="document.getElementById('{{ example.id }}').style.visibility = 'visible'">
                <div class="card-header bg-info text-white">
                    {% if lang == 'FR' %}{{ example.french }}{% else %}{{ example.japanese }}{% endif %}
                </div>
            </a>
            <a onclick="document.getElementById('{{ example.id }}').style.visibility = 'hidden'">
                <div>
                    <ul class="list-group list-group-flush" id='{{ example.id }}' style="visibility: hidden">
                        <li class="list-group-item bg-light">{% if lang == 'FR' %}{{ example.japanese }}{% else %}{{ example.french }}{% endif %}</li>
                    </ul>
                </div>
            </a>
        </div>
        <hr>
    {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script>
$(function(){
    $("#example").bsMultiSelect();
});
</script>
{% endblock %}

kata/templates/katatoeba/validate.html
{% extends 'base.html' %}

{% block content %}
<script>
var valids = []
var goners = []
var comments = {}
function out(array, id){
    if(array.includes(id)){
        var index = array.indexOf(id);
        array.splice(index, 1);
    }
}
function update(){
    document.getElementById('goners').value = goners.join();
    document.getElementById('valids').value = valids.join();
    document.getElementById('comments').value = JSON.stringify(comments);
}
function remove(id){
    if(!goners.includes(id)) goners.push(id);
    out(valids, id);
    $('#r_'+id).removeClass('bg-danger').addClass('bg-dark').addClass('text-white');
    $('#v_'+id).addClass('bg-success').removeClass('bg-dark').removeClass('text-white');
    update();
}
function validate(id){
    if(!valids.includes(id)) valids.push(id);
    out(goners, id);
    $('#r_'+id).addClass('bg-danger').removeClass('bg-dark').removeClass('text-white');
    $('#v_'+id).removeClass('bg-success').addClass('bg-dark').addClass('text-white');
    update();
}
function comment(id){
    comments[id] = $('#c_'+id).val();
    update();
    alert('Comment updated');
}
</script>

<div class="container my-4">
    {% for example in examples %}
        <div class="card" id='{{ example.id }}' style="width: 40rem;">
            <a href="../edit/{{ example.id }}">
                <div class="card-header bg-info text-white">
                    {{ example.japanese }}
                </div>
            </a>
            <ul class="list-group list-group-flush" id='{{ example.id }}'>
                <li class="list-group-item bg-light">{{ example.french }}</li>
                <a onclick="remove('{{ example.id }}')">
                    <li class="list-group-item bg-danger" id="r_{{ example.id }}">Invalidate</li>
                </a>
                <a onclick="validate('{{ example.id }}')">
                    <li class="list-group-item bg-success" id="v_{{ example.id }}">Validate</li>
                </a>
                <li class="list-group-item bg-warning">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control w-75" id="c_{{ example.id }}" value="{{ example.comment }}">
                        <div class="input-group-append">
                            <button class="btn btn-primary" onclick="comment('{{ example.id }}')">
                                Set comment
                            </button>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <hr>
    {% endfor %}

    <form>
        {% csrf_token %}
        <input type='hidden' id='valids' name='valids'>
        <input type='hidden' id='goners' name='goners'>
        <input type='hidden' id='comments' name='comments'>
        <button type='submit' formmethod="post" class="btn btn-primary waves-effect waves-light">
            Confirms
        </button>
    </form>
</div>
{% endblock %}